# Jekyll configuration for Open SDG platform
#
# You will need to change all of the Github-related variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"
#
# NOTE: This "production" version only contains differences from _config.yml.

baseurl: ""
environment: production
# Replace my-github-org and open-sdg-data-starter as needed.
remotedatabaseurl: "https://SDG-kyrgyzstan.github.io/open-sdg-data-starter"

jekyll_get_json:
  - data: meta
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/meta/all.json'
  - data: headlines
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/sdg-data/headline/all.json'
  - data: schema
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/sdg-data/meta/schema.json'
  - data: reporting
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-data-starter/stats/reporting.json'
  - data: translations
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.0.json'

analytics:
  # For production, you likely want to enter a Google Analytics code below.
  ga_prod: ''
  
  # Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-get-json
  
# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-get-json

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@0.5.0

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
